#define	KEYWORD		1 
#define IDENTIFIER	2
#define NUMBER		3
#define ASSIGN		4
#define OPEN_BRACE	5
#define CLOSE_BRACE	6
#define OPEN_PARAN	7
#define CLOSE_PARAN	8
#define SEMICOLON	9
#define STRING_LTR	10