#define	TOK_WHILE		'w'
#define TOK_BEGIN		'b'
#define TOK_END			'e'
#define TOK_COMP_EQ		'x'
#define TOK_COMP_NEQ	'y'
#define TOK_IDENTIFIER	'i'
#define TOK_ASSIGNMENT	'='
#define TOK_SEMICOLON	';'
#define TOK_NUMBER		'n'
#define TOK_ADD			'+'
#define TOK_MULT		'*'
#define TOK_SUB			'-'
#define TOK_OPEN_PARAN	'('
#define TOK_CLOSE_PARAN ')'
#define TOK_EOF			'$'

#define TOK_INVALID		'%'